// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ca92M5XCKUiunMiheZ0H8KVxYZFVcfk',
    appId: '1:1080891804344:web:2c25e14eee34c60766824d',
    messagingSenderId: '1080891804344',
    projectId: 'carparksys',
    authDomain: 'carparksys.firebaseapp.com',
    databaseURL: 'https://carparksys-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carparksys.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0HvBjCuM4Lu2SSoK03Yt2bkEkx4yjdkI',
    appId: '1:1080891804344:android:9b3acceee1261b9466824d',
    messagingSenderId: '1080891804344',
    projectId: 'carparksys',
    databaseURL: 'https://carparksys-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carparksys.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuMLzdYexw00x0leSSLIuKOenSTqrvoL0',
    appId: '1:1080891804344:ios:deca85b909a8738466824d',
    messagingSenderId: '1080891804344',
    projectId: 'carparksys',
    databaseURL: 'https://carparksys-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carparksys.appspot.com',
    androidClientId: '1080891804344-9faa7ovfr1odgf16d4003iie65ik2q59.apps.googleusercontent.com',
    iosClientId: '1080891804344-4lbjfghnf503utl106n5cbshhjsl4knt.apps.googleusercontent.com',
    iosBundleId: 'com.proto.carparksys',
  );
}
